# Generated by Django 3.2 on 2021-04-18 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0003_auto_20210401_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='recentylistenedplaylist',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Recently_Listened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datelistened', models.DateTimeField(auto_now_add=True)),
                ('songid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.musicdata')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
